{% set version = '0.6.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/smd_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/smd/smd_{{ version }}.tar.gz
  sha256: 324a80e3d4e8e0ea92775e722c63fc3ebbfa0413f23e4b248301e27c859a74db

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass >=7.3_50
  run:
    - r-base
    - r-mass >=7.3_50

test:
  commands:
    - $R -e "library('smd')"           # [not win]
    - "\"%R%\" -e \"library('smd')\""  # [win]

about:
  home: https://docs.novisci.com/smd/
  license: MIT
  summary: Computes standardized mean differences and confidence intervals for multiple data
    types based on Yang, D., & Dalton, J. E. (2012) <http://www.lerner.ccf.org/qhs/software/lib/stddiff.pdf>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: smd
# Type: Package
# Title: Compute Standardized Mean Differences
# Version: 0.6.6
# Authors@R: c(person("Bradley", "Saul", role = c("aut", "cre"), email = "bsaul@novisci.com"), person("Alex", "Breskin", role = c("ctb"), email = "abreskin@novisci.com"), person("Catie", "Wiener", role = c("ctb"), email = "cwiener@novisci.com"), person("Matt", "Phelan", role = c("ctb"), email = "mphelan@novisci.com"))
# Description: Computes standardized mean differences and confidence intervals for multiple data types based on Yang, D., & Dalton, J. E. (2012) <http://www.lerner.ccf.org/qhs/software/lib/stddiff.pdf>.
# Imports: MASS (>= 7.3-50), methods (>= 3.5.1)
# Suggests: testthat, stddiff, tableone, knitr, dplyr, purrr, markdown, rmarkdown
# License: MIT + file LICENSE
# URL: https://docs.novisci.com/smd/
# BugReports: https://gitlab.novisci.com/nsstat/smd/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# VignetteBuilder: knitr
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2020-10-13 20:13:52 UTC; bsaul
# Author: Bradley Saul [aut, cre], Alex Breskin [ctb], Catie Wiener [ctb], Matt Phelan [ctb]
# Maintainer: Bradley Saul <bsaul@novisci.com>
# Date/Publication: 2020-10-22 09:20:02 UTC
